# Configuration file for bacterial repeat analysis pipeline

# Path to the input genome assembly FASTA file
assembly: "data/genomes/merrill-23.fasta"

# Output directory for results
output_dir: "results/repeat_analysis"

# Number of threads to use for parallelizable tools
threads: 8

# Species for RepeatMasker (bacteria is default)
species: "bacteria"

# RepeatMasker options specifically for bacterial genomes
# -xsmall: Returns sequences with repeats in lowercase (soft masking)
# -pa N: Runs the search in parallel using N processors
# -species bacteria: Use bacteria-specific repeat database
# -noint: Skip interspersed repeats, focus on simple repeats and low complexity regions
repeatmasker_options: "-xsmall -pa {} -species bacteria -noint"

# RED options optimized for bacterial genomes
# -frp=0.01: Lower threshold for bacterial genomes as they typically have fewer repeats
# -k=13: Smaller k-mer size appropriate for bacterial genomes
# -tel=0: No telomeric repeats in bacteria
# -itr=1: Include inverted terminal repeats common in bacterial IS elements
red_options: ""

# Minimum length of interspersed repeats to report (in bp)
# For bacterial genomes, detecting shorter repeats is beneficial
min_repeat_length: 30

# Minimum sequence identity for interspersed repeats (%)
# Higher threshold for bacterial genomes to reduce false positives
min_repeat_identity: 95

# Bacterial-specific configuration
# Enable IS element analysis (common in bacterial genomes)
analyze_is_elements: true

# Enable transposon analysis (common in bacterial genomes)
analyze_transposons: true

# Word size for BLAST in repeat detection (smaller for bacterial genomes)
blast_word_size: 11
